baseurl = "/"
languageCode = "en-us"
enableEmoji = true
title = "React.js and Draft.js expert for hire"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

[taxonomies]
  series = "series"

[params]
  description = "I build and design interfaces for startups with react.js and draft.js. Get in touch to make your product shine!"
  sitemapurl = "https://reactrocket.com"

[author]
  name = "Julian Krispel"
  email = "julian@reactrocket.com"

[outputs]
home = [ "RSS", "HTML"]

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"
